<?php

return array(
    'logo'                => '/static/akali/images/logo.png',
    'wap_logo'            => '',
    'name'                => '草帽跨境-跨境电商综合服务平台',
    'url'                 => 'www.caomaokj.com',
    'email'               => '972581428@qq.com',
    'seo_title'           => '草帽跨境',
    'seo_keywords'        => '跨境电商平台,跨境电商物流,跨境电商活动,跨境电商资讯,跨境电商直播,草帽跨境',
    'seo_description'     => '跨境电商平台,跨境电商物流,跨境电商活动,跨境电商资讯,跨境电商直播,草帽跨境',
    'tel'                 => '',
    'contacts'            => '',
    'fax'                 => '',
    'address'             => '广州市白云区',
    'qq'                  => '617416179',
    'phone'               => '',
    'icp'                 => '',
    'two_code'            => '',
    'copyright'           => 'COPYRIGHT © 2016-2017亚马逊导航 ALL RIGHTS RESERVED.',
    'attach_maxsize'      => '53428800',
    'attach_type'         => 'jpg,jpeg,gif,png,ico',
    'watermark_enable'    => '0',
    'watemard_text'       => '草帽跨境',
    'watemard_text_size'  => '18',
    'watemard_text_color' => '#000000',
    'watemard_text_face'  => '1.ttf',
    'watemard_satisfy'    => '300*100',
    'watermark_img'       => '/static/admin/Images/warks.png',
    'watermark_pct'       => '80',
    'watermark_pos'       => '9',
);
